/* Login Actions */
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const REHYDRATE_USER = 'REHYDRATE_USER';
/* Config Actions */
export const LOAD_CONFIG = 'LOAD_CONFIG';
export const LOAD_CONFIG_ERROR = 'LOAD_CONFIG_ERROR';
/* Parts Search Actions */
export const PARTS_SEARCH = 'PARTS_SEARCH';
export const PARTS_SEARCH_START = 'PARTS_SEARCH_START';
export const PARTS_SEARCH_ERROR = 'PARTS_SEARCH_ERROR';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
/* Cart Actions */
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const ADJUST_QUANTITY = 'ADJUST_QUANTITY';
/* Notification Actions */
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const SHOW_SUCCESS_MESSAGE = 'SHOW_SUCCESS_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
/* Parts Orders Actions */
export const GET_PARTS_ORDERS_SUCCESS = 'GET_PARTS_ORDERS_SUCCESS';
export const GET_PARTS_ORDERS_FAILURE = 'GET_PARTS_ORDERS_FAILURE';
export const CREATE_PARTS_ORDER_START = 'CREATE_PARTS_ORDER_START';
export const CREATE_PARTS_ORDER_SUCCESS = 'CREATE_PARTS_ORDER_SUCCESS';
export const CREATE_PARTS_ORDER_FAILURE = 'CREATE_PARTS_ORDER_FAILURE';
/* Inventory Actions */
export const EDIT_ITEM = 'EDIT_ITEM';
export const GET_INVENTORY = 'GET_INVENTORY';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const SHOW_INFO_MESSAGE = 'SHOW_INFO_MESSAGE';

/* Purchase Order Actions */
export const GET_PURCHASE_ORDERS_START = 'GET_PURCHASE_ORDERS_START';
export const GET_PURCHASE_ORDERS_SUCCESS = 'GET_PURCHASE_ORDERS_SUCCESS';
export const GET_PURCHASE_ORDERS_FAILURE = 'GET_PURCHASE_ORDERS_FAILURE';
export const UPDATE_RECEIVE_PART_ORDER = 'UPDATE_RECEIVE_PART_ORDER';
export const UPDATE_RECEIVE_PART_ORDER_FAILURE = 'UPDATE_RECEIVE_PART_ORDER_FAILURE';
